import type { Metadata } from "next";
import { Flow_Circular } from "next/font/google";
import Navbar from "../components/navbarlanding/navbar"
import Footer from "../components/landingSections/footer"
import "../styles/globals.css";

const flowCircular = Flow_Circular({
  subsets: ["latin"],
  weight: "400",
});


export const metadata: Metadata = {
  title: "PlumSend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body >
          <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
