import type { Metadata } from "next";
import { Nunito,Montserrat } from "next/font/google";
import Navbar from "./components/navbarlanding/navbar"
import Footer from "./components/landingSections/footer"
import "./styles/globals.css";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PlumSend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Navbar/>
        {children}
        <Footer/>
        </div></body>
    </html>
  );
}
